In [69]:
# импортируем библиотеки 
import pandas as pd

In [70]:
df=pd.read_excel("C:\\Users\\Sergey\\OneDrive\\Документы\\VTB\\123.xlsx")

In [112]:
df.head(20)

,mcc,name,num_magazine,address,country,city,lat,lon,postal_code,country_iso_code,region,city_district,street,house,block,legal_name,inn,tsp_name,magazine,name_new
0,5941,Спортмастер,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер
1,5691,Спортмастер,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер
2,5940,Спортмастер CO. LTD.,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер CO. LTD.
3,5941,Спортмастер,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер
4,5941,Спортмастер,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер
5,5941,Спортмастер SHOP,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер SHOP
6,5941,Спортмастер,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер
7,5941,Спортмастер,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер
8,5655,Спортмастер,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер
9,5941,Спортмастер,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер
10,5655,Спортмастер,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер
11,5941,Спортмастер,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер
12,5655,Спортмастер,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер
13,5941,Спортмастер SHOP,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер SHOP
14,5941,Спортмастер,114,"Смоленская пл., д. 6, стр. 1",Россия,Москва,55.748655,37.583535,121099,643,Москва,Москва,Смоленская пл.,д. 6,стр. 1,"ООО ""СПОРТМАСТЕР""",nan,Спортмастер 114,NaN,Спортмастер 114
15,5941,Спортмастер 147,147,"г. Жуковский, ул. Гагарина, д. 51",Россия,Жуковский,55.606858,38.095359,140180,643,Московская область,Жуковский,ул. Гагарина,д. 51,-,"ООО ""СПОРТМАСТЕР""",nan,Спортмастер 147,-,Спортмастер 147
16,5941,Спортмастер 171,171,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер 171
17,5941,Спортмастер 188,188,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,Спортмастер 188
18,5941,Спортмастер 190,190,"г. Химки, Ленинградское ш., вл. 5",Россия,Химки,55.888765,37.433526,141402,643,Московская область,Химки,Ленинградское ш.,-,"Ленинградское ш., вл. 5","ООО ""СПОРТМАСТЕР""",7728551528,Спортмастер 190,"ТЦ ""ЛИГА""",Спортмастер 190
19,5941,Спортмастер 193,193,"МКАД, 87-й километр, 8, Москва",Россия,Москва,55.898588,"55.898588, 37.629385",127543,643,Москова,Москва,"МКАД, 87-й километр",-,-,"ООО ""СПОРТМАСТЕР""",nan,Спортмастер 193,"ТЦ ""ЧАС ПИК""",Спортмастер 193

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2046 entries, 0 to 2045
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   `mcc`                2046 non-null   int64
 1    `name`              2046 non-null   object
 2   № magazine           1926 non-null   object
 3    `address`           1 non-null      object
 4    `country`           1 non-null      object
 5    `city`              1 non-null      object
 6    `lat`               1 non-null      float64
 7    `lon`               1 non-null      float64
 8    `postal_code`       282 non-null    float64
 9    `country_iso_code`  1 non-null      object
 10   `region`            0 non-null      float64
 11   `city_district`     0 non-null      float64
 12   `street`            1 non-null      object
 13   `house`             1 non-null      float64
 14   `block`             0 non-null      float64
 15   `legal_name`        1305 non-null   object
 16   `inn`               1305 non-null   float64
 17   `tsp_name`          1305 non-null   object
 18  magazine             1163 non-null   object
dtypes: float64(8), int64(1), object(10)
memory usage: 303.8+ KB

In [73]:
df = df.rename(columns=
               {
                   '`mcc`': 'mcc',
                   ' `name`': 'name', 
                   ' `address`': 'address', 
                   ' `country`': 'country',
               ' `city`': 'city',
               ' `lat`': 'lat',
               ' `lon`': 'lon',
                   ' `postal_code`': 'postal_code',
                   ' `country_iso_code`': 'country_iso_code',
                   ' `street`': 'street',
                   ' `house`': 'house',
                   ' `block`': 'block',
                   ' `block`': 'block',
                   ' `legal_name`': 'legal_name',
                   ' `inn`': 'inn',
                   ' `region`': 'region',
                   ' `city_district`': 'city_district',
                   '№ magazine': 'num_magazine',
                   ' `tsp_name`': 'tsp_name'
               })

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2046 entries, 0 to 2045
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mcc               2046 non-null   int64
 1   name              2046 non-null   object
 2   num_magazine      1926 non-null   object
 3   address           1 non-null      object
 4   country           1 non-null      object
 5   city              1 non-null      object
 6   lat               1 non-null      float64
 7   lon               1 non-null      float64
 8   postal_code       282 non-null    float64
 9   country_iso_code  1 non-null      object
 10  region            0 non-null      float64
 11  city_district     0 non-null      float64
 12  street            1 non-null      object
 13  house             1 non-null      float64
 14  block             0 non-null      float64
 15  legal_name        1305 non-null   object
 16  inn               1305 non-null   float64
 17  tsp_name          1305 non-null   object
 18  magazine          1163 non-null   object
dtypes: float64(8), int64(1), object(10)
memory usage: 303.8+ KB

In [75]:
#df['inn']=df['inn'].fillna(0)
df['inn']=df['inn'].astype(str)

In [76]:
df['inn'].unique()

array(['nan', '7728551528.0'], dtype=object)

In [77]:
df['num_magazine'].unique()

array([nan, 114, 147, 171, 188, 190, 193, 244, 475, 5016, 5017, 5066,
       5073, 5089, 5106, 5156, 5205, 5227, 5349, 5351, 5354, 5419, 5474,
       5496, 5551, 5657, 5659, 5665, 5685, 5799, 5818, 5976, 5984, 6018,
       6094, 6113, 6163, 6217, 6224, 6235, 6245, 6263, 6302, 6357, 711,
       821, 824, 842, 868, 974, 151, 166, 175, 200, 358, 478, 486, 488,
       492, 5128, 5206, 5209, 5405, 5447, 5448, 5467, 5468, 5470, 5569,
       5621, 5676, 5755, 5757, 5798, 5829, 5878, 6067, 6081, 6114, 6219,
       6222, 6266, 6269, 6379, 714, 723, 755, 782, 838, 884, 888, 896, 1,
       2, 123, 135, 178, 189, 191, 489, 491, 493, 5048, 5054, 5097, 5114,
       5116, 5117, 5167, 5224, 5233, 5305, 5312, 5320, 5342, 5380, 5406,
       5407, 5408, 5410, 5411, 5445, 5464, 5522, 5550, 5568, 5574, 5575,
       5577, 5708, 5725, 5782, 5785, 5825, 5850, 5866, 5879, 5883, 5893,
       5967, 6101, 6126, 6140, 6152, 6199, 6202, 6212, 6223, 6244, 6298,
       6351, 6378, 6381, 6391, 6409, 730, 734, 781, 833, 855, 883, 895,
       912, 932, 971, 973, 3, 5200, 125, 153, 329, 5015, 5018, 5052, 5065,
       5100, 5115, 5149, 5159, 5165, 5182, 5265, 5286, 5321, 5322, 5409,
       5477, 5478, 5491, 5494, 5528, 5565, 5588, 5630, 5631, 5658, 5720,
       5766, 5803, 5954, 5988, 6203, 6214, 6246, 6258, 6305, 6308, 6318,
       6338, 6392, 6441, 705, 712, 720, 731, 866, 898, 970, 8, 6518, 6673,
       6431, 6491, 6473, 6698, 6459, 5524, 6733, 6690, 6659, 6517, 6787,
       6499, 6817, 7, 10, 9, 6894, 6664, 5605, 5601, 5595, 5591, 5587,
       5582, 5581, 5539, 5538, 5520, 5515, 5495, 5490, 5480, 5473, 5461,
       5460, 5450, 5449, 5446, 5442, 5433, 5422, 5389, 5387, 5378, 5377,
       5367, 5366, 5340, 5339, 5324, 5307, 5306, 5269, 5267, 5266, 5263,
       5261, 5259, 5257, 5255, 5232, 5230, 5228, 5208, 5202, 5198, 5197,
       5196, 5172, 5158, 5154, 5150, 5143, 5118, 5107, 5105, 5102, 5101,
       5099, 933, 931, 871, 870, 861, 836, 819, 809, 771, 762, 756, 750,
       737, 735, 725, 722, 719, 715, 708, 706, 6931, 6925, 6897, 6805,
       6794, 6793, 6730, 6721, 6716, 6703, 6685, 6653, 6541, 6495, 6479,
       6478, 6477, 6475, 6444, 6443, 6442, 6439, 6421, 6382, 6376, 6355,
       6345, 6342, 6340, 6337, 6320, 6319, 6310, 6309, 6306, 6296, 6295,
       6267, 6264, 6242, 6236, 6225, 6221, 6216, 6215, 6204, 6197, 6155,
       6154, 6153, 6149, 6131, 6117, 6111, 6102, 6100, 6079, 6070, 6069,
       6068, 6052, 6051, 6050, 6037, 6035, 6020, 6019, 6004, 6002, 5999,
       5995, 5992, 5991, 5987, 5985, 5971, 5966, 5957, 5944, 5943, 5942,
       5892, 5887, 5886, 5885, 5877, 5876, 5875, 5831, 5830, 5824, 5819,
       5816, 5815, 5804, 5797, 5781, 5780, 5765, 5752, 5751, 5750, 5747,
       5741, 5738, 5737, 5718, 5713, 5709, 5699, 5690, 5686, 5682, 5681,
       5674, 5667, 5635, 5064, 5063, 5059, 5055, 5051, 5047, 5037, 5030,
       5022, 5020, 5019, 498, 496, 495, 494, 485, 482, 480, 479, 470, 466,
       465, 464, 460, 430, 426, 421, 420, 413, 411, 410, 406, 400, 327,
       296, 293, 286, 285, 282, 272, 270, 269, 266, 264, 254, 245, 210,
       207, 201, 194, 192, 160, 159, 143, 138, 126, 117, 6526, 6904, 6935,
       6907, 6899, ' Спортмастер', ' Демикс 6929', ' Demix_6357',
       ' Urban Vibes_6702 ТЦ \\"Zеленопарк\\"', ' Urban Vibes_6543',
       ' Demix 6910', 6924, 'Спортмастер_mrm', 6657, ' Demix_6298',
       ' Demix_6472 ТЦ \\"Солнечный\\"', ' Demix_6438', 6946,
       ' Demix 6923', ' Urbanvibes', ' Urban Vibes 6905',
       ' Urban Vibes_6671', ' Urban Vibes 6932', ' Demix_6391',
       ' Urban Vibes_6701 ТЦ \\"Европолис\\"', ' 1МП СМ', 'Спортмастер',
       ' Demix_6493', 6934, 6945, 6722, 6978, 6676, 6453, 6906],
      dtype=object)

In [78]:
grouped = df['name'].groupby(df['num_magazine']).agg('count').sort_values(ascending=False)
grouped.head(20)

num_magazine
 1МП СМ    32
5887       11
6495       11
5720       10
5522       10
5106       10
114        10
884        10
6246       10
5159       10
5741       10
5766        9
5816        9
5128        9
898         9
5054        9
5209        9
6305        9
5411        9
5957        8
Name: name, dtype: int64

In [125]:
df.loc[df['num_magazine'] == 5816]

,mcc,name,num_magazine,address,country,city,lat,lon,postal_code,country_iso_code,region,city_district,street,house,block,legal_name,inn,tsp_name,magazine,name_new
1061,5655,MA0000215288,5816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ООО \""СПОРТМАСТЕР\""",7728551528.0,Спортмастер 5816,ТРЦ ЯркоМолл,MA0000215288
1788,5655,TMA000021528,5816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ООО \""СПОРТМАСТЕР\""",7728551528.0,Спортмастер 5816,ТРЦ ЯркоМолл,TMA000021528
1801,5655,AMA000021528,5816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ООО \""СПОРТМАСТЕР\""",7728551528.0,Спортмастер 5816,ТРЦ ЯркоМолл,AMA000021528
1828,5655,UMA000021528,5816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ООО \""СПОРТМАСТЕР\""",7728551528.0,Спортмастер 5816,ТРЦ ЯркоМолл,UMA000021528
1833,5655,BMA000021528,5816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ООО \""СПОРТМАСТЕР\""",7728551528.0,Спортмастер 5816,ТРЦ ЯркоМолл,BMA000021528
1879,5655,5MA000021528,5816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ООО \""СПОРТМАСТЕР\""",7728551528.0,Спортмастер 5816,ТРЦ ЯркоМолл,5MA000021528
1881,5655,NMA000021528,5816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ООО \""СПОРТМАСТЕР\""",7728551528.0,Спортмастер 5816,ТРЦ ЯркоМолл,NMA000021528
1883,5655,VMA000021528,5816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ООО \""СПОРТМАСТЕР\""",7728551528.0,Спортмастер 5816,ТРЦ ЯркоМолл,VMA000021528
1884,5655,HMA000021528,5816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ООО \""СПОРТМАСТЕР\""",7728551528.0,Спортмастер 5816,ТРЦ ЯркоМолл,HMA000021528

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2046 entries, 0 to 2045
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mcc               2046 non-null   int64
 1   name              2046 non-null   object
 2   num_magazine      1926 non-null   object
 3   address           1 non-null      object
 4   country           1 non-null      object
 5   city              1 non-null      object
 6   lat               1 non-null      float64
 7   lon               1 non-null      float64
 8   postal_code       282 non-null    float64
 9   country_iso_code  1 non-null      object
 10  region            0 non-null      float64
 11  city_district     0 non-null      float64
 12  street            1 non-null      object
 13  house             1 non-null      float64
 14  block             0 non-null      float64
 15  legal_name        1305 non-null   object
 16  inn               2046 non-null   object
 17  tsp_name          1305 non-null   object
 18  magazine          1163 non-null   object
dtypes: float64(7), int64(1), object(11)
memory usage: 303.8+ KB

In [80]:
df['name_new'] = df['name'].copy()

In [81]:
i=114

df.loc[df['num_magazine'] == i, 'address'] = 'Смоленская пл., д. 6, стр. 1'
df.loc[df['num_magazine'] == i, 'country'] = 'Россия'
df.loc[df['num_magazine'] == i,'city']='Москва'
df.loc[df['num_magazine'] == i,'postal_code']='121099'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'Смоленская пл.'
df.loc[df['num_magazine'] == i,'house'] = 'д. 6'
df.loc[df['num_magazine'] == i,'block'] = 'стр. 1'
df.loc[df['num_magazine'] == i,'lat'] = '55.748655'
df.loc[df['num_magazine'] == i,'lon'] = '37.583535'
df.loc[df['num_magazine'] == i,'region'] = 'Москва'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 114'
df.loc[df['num_magazine'] == i,'name'] = 'Спортмастер'

In [82]:

#df.loc[df['num_magazine'] == 114]

In [83]:
i=898
df.loc[df['num_magazine'] == i,'address']='МКАД 24-й км., д.1'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='Москва'
df.loc[df['num_magazine'] == i,'postal_code']='142715'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'МКАД 24-й км.'
df.loc[df['num_magazine'] == i,'house'] = 'д. 1'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '55.586807'
df.loc[df['num_magazine'] == i,'lon'] = '37.724975'
df.loc[df['num_magazine'] == i,'region'] = 'Москва'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ Вегас'
df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 898'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
df.loc[df['num_magazine'] == i,'name'] = 'Спортмастер'
#df.loc[df['num_magazine'] == i]

In [84]:
i=849
df.loc[df['num_magazine'] == i,'address']='ул. Вавилова, д. 3, стр. 1'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='Москва'
df.loc[df['num_magazine'] == i,'postal_code']='119334'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'ул. Вавилова'
df.loc[df['num_magazine'] == i,'house'] = 'д. 3'
df.loc[df['num_magazine'] == i,'block'] = 'стр. 1'
df.loc[df['num_magazine'] == i,'lat'] = '55.706883'
df.loc[df['num_magazine'] == i,'lon'] = '37.592096'
df.loc[df['num_magazine'] == i,'region'] = 'Москва'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ Гагаринский'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 849'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i]

In [85]:
i=147
df.loc[df['num_magazine'] == i,'address']='г. Жуковский, ул. Гагарина, д. 51'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='Жуковский'
df.loc[df['num_magazine'] == i,'postal_code']='140180'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'ул. Гагарина'
df.loc[df['num_magazine'] == i,'house'] = 'д. 51'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '55.606858'
df.loc[df['num_magazine'] == i,'lon'] = '38.095359'
df.loc[df['num_magazine'] == i,'region'] = 'Московская область'
df.loc[df['num_magazine'] == i,'magazine'] = '-'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 147'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i]

In [86]:
i=190
df.loc[df['num_magazine'] == i,'address']='г. Химки, Ленинградское ш., вл. 5'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='Химки'
df.loc[df['num_magazine'] == i,'postal_code']='141402'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'Ленинградское ш.'
df.loc[df['num_magazine'] == i,'house'] = '-'
df.loc[df['num_magazine'] == i,'block'] = 'Ленинградское ш., вл. 5'
df.loc[df['num_magazine'] == i,'lat'] = '55.888765'
df.loc[df['num_magazine'] == i,'lon'] = '37.433526'
df.loc[df['num_magazine'] == i,'region'] = 'Московская область'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "ЛИГА"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 190'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [87]:
i=193
df.loc[df['num_magazine'] == i,'address']='МКАД, 87-й километр, 8, Москва'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='Москва'
df.loc[df['num_magazine'] == i,'postal_code']='127543'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'МКАД, 87-й километр'
df.loc[df['num_magazine'] == i,'house'] = '-'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '55.898588'
df.loc[df['num_magazine'] == i,'lon'] = '55.898588, 37.629385'
df.loc[df['num_magazine'] == i,'region'] = 'Москова'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "ЧАС ПИК"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 193'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [88]:
i=244
df.loc[df['num_magazine'] == i,'address']='г. Дзержинск, пр-т Ленина д. 66'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Дзержинск'
df.loc[df['num_magazine'] == i,'postal_code']='606000'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'пр-т Ленина'
df.loc[df['num_magazine'] == i,'house'] = 'д. 66'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '56.236986'
df.loc[df['num_magazine'] == i,'lon'] = '43.462820'
df.loc[df['num_magazine'] == i,'region'] = 'Москова'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "Дзержинец"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 244'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [89]:
i=5017
df.loc[df['num_magazine'] == i,'address']='г. Тверь, пр-т Калинина, д. 15, стр. 1'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Тверь'
df.loc[df['num_magazine'] == i,'postal_code']='170001'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'пр-т Калинина'
df.loc[df['num_magazine'] == i,'house'] = 'д. 15'
df.loc[df['num_magazine'] == i,'block'] = 'стр. 1'
df.loc[df['num_magazine'] == i,'lat'] = '56.853720'
df.loc[df['num_magazine'] == i,'lon'] = '35.865615'
df.loc[df['num_magazine'] == i,'region'] = 'Тверь'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "Рубин"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5017'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [90]:
i=5073
df.loc[df['num_magazine'] == i,'address']='г. Балашиха, 20, микрорайон ЦОВБ'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Балашиха'
df.loc[df['num_magazine'] == i,'postal_code']='143914'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = '20, микрорайон ЦОВБ'
df.loc[df['num_magazine'] == i,'house'] = '-'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '55.784491'
df.loc[df['num_magazine'] == i,'lon'] = '37.877913'
df.loc[df['num_magazine'] == i,'region'] = 'Балашиха'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "Идея"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5073'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [91]:
i=5089
df.loc[df['num_magazine'] == i,'address']='г. Электросталь,ул. Корешкова, 3'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Электросталь'
df.loc[df['num_magazine'] == i,'postal_code']='144003'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'ул. Корешкова'
df.loc[df['num_magazine'] == i,'house'] = '3'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '55.784633'
df.loc[df['num_magazine'] == i,'lon'] = '38.447391'
df.loc[df['num_magazine'] == i,'region'] = 'Электросталь'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "Фэмили Парк"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5089'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [92]:
i=5720
df.loc[df['num_magazine'] == i,'address']='г. Ярославль, ул. Победы, д.41'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Ярославль'
df.loc[df['num_magazine'] == i,'postal_code']='150000'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = ' ул. Победы'
df.loc[df['num_magazine'] == i,'house'] = 'д.41'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '57.627759'
df.loc[df['num_magazine'] == i,'lon'] = '39.871167'
df.loc[df['num_magazine'] == i,'region'] = 'Ярославль'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "Аура"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5720'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [93]:
i=5720
df.loc[df['num_magazine'] == i,'address']='г. Ярославль, ул. Победы, д.41'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Ярославль'
df.loc[df['num_magazine'] == i,'postal_code']='150000'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = ' ул. Победы'
df.loc[df['num_magazine'] == i,'house'] = 'д.41'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '57.627759'
df.loc[df['num_magazine'] == i,'lon'] = '39.871167'
df.loc[df['num_magazine'] == i,'region'] = 'Ярославль'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "Аура"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5720'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [94]:
i=884
df.loc[df['num_magazine'] == i,'address']='г. Подольск, ул. Комсомольская, д.46'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Подольск'
df.loc[df['num_magazine'] == i,'postal_code']='142100'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = ' ул. Комсомольская'
df.loc[df['num_magazine'] == i,'house'] = 'д.46'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '55.430845'
df.loc[df['num_magazine'] == i,'lon'] = '37.548384'
df.loc[df['num_magazine'] == i,'region'] = 'Ярославль'
df.loc[df['num_magazine'] == i,'magazine'] = '-"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 884'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [95]:
i=884
df.loc[df['num_magazine'] == i,'address']='г. Подольск, ул. Комсомольская, д.46'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Подольск'
df.loc[df['num_magazine'] == i,'postal_code']='142100'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = ' ул. Комсомольская'
df.loc[df['num_magazine'] == i,'house'] = 'д.46'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '55.430845'
df.loc[df['num_magazine'] == i,'lon'] = '37.548384'
df.loc[df['num_magazine'] == i,'region'] = 'Ярославль'
df.loc[df['num_magazine'] == i,'magazine'] = '-"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 884'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [96]:
i=6246
df.loc[df['num_magazine'] == i,'address']='г. Москва, ул. Бибиревская, д.10, к.2'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Москва'
df.loc[df['num_magazine'] == i,'postal_code']='142100'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = ' ул. Бибиревская'
df.loc[df['num_magazine'] == i,'house'] = 'д.10'
df.loc[df['num_magazine'] == i,'block'] = 'к. 2'
df.loc[df['num_magazine'] == i,'lat'] = '55.881510'
df.loc[df['num_magazine'] == i,'lon'] = '37.602481'
df.loc[df['num_magazine'] == i,'region'] = 'Ярославль'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "Лента"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 6246'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [97]:
i=5159
df.loc[df['num_magazine'] == i,'address']='г. Зеленоград, пгт. Ржавки, 2 мкр'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Зеленоград'
df.loc[df['num_magazine'] == i,'postal_code']='141552'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'пгт. Ржавки'
df.loc[df['num_magazine'] == i,'house'] = '2 мкр'
df.loc[df['num_magazine'] == i,'block'] = '_'
df.loc[df['num_magazine'] == i,'lat'] = '55.998081'
df.loc[df['num_magazine'] == i,'lon'] = '37.252659'
df.loc[df['num_magazine'] == i,'region'] = 'Москва'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "Zеленопарк"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 6246'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [98]:
i=5128
df.loc[df['num_magazine'] == i,'address']='г. Ногинск, ул.Соборная, д. 12'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Ногинск'
df.loc[df['num_magazine'] == i,'postal_code']='142400'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'ул.Соборная'
df.loc[df['num_magazine'] == i,'house'] = 'д. 12'
df.loc[df['num_magazine'] == i,'block'] = '_'
df.loc[df['num_magazine'] == i,'lat'] = '55.853218'
df.loc[df['num_magazine'] == i,'lon'] = '38.442028'
df.loc[df['num_magazine'] == i,'region'] = 'Московский регион'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "На Соборной площади"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5128'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [101]:
i=5054
df.loc[df['num_magazine'] == i,'address']='г. Челябинск, ул. Труда, д. 203'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Челябинск'
df.loc[df['num_magazine'] == i,'postal_code']='454080'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'ул. Труда'
df.loc[df['num_magazine'] == i,'house'] = 'д. 203'
df.loc[df['num_magazine'] == i,'block'] = '_'
df.loc[df['num_magazine'] == i,'lat'] = '55.171051'
df.loc[df['num_magazine'] == i,'lon'] = '61.355976'
df.loc[df['num_magazine'] == i,'region'] = 'Челябинская обл.'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТРК "Родник"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5054'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [106]:
i=5209
df.loc[df['num_magazine'] == i,'address']='г. Серпухов,  Борисовское ш., д. 1'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Серпухов'
df.loc[df['num_magazine'] == i,'postal_code']='142200'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'Борисовское ш.'
df.loc[df['num_magazine'] == i,'house'] = 'д. 1'
df.loc[df['num_magazine'] == i,'block'] = '_'
df.loc[df['num_magazine'] == i,'lat'] = '54.917520'
df.loc[df['num_magazine'] == i,'lon'] = '37.426501'
df.loc[df['num_magazine'] == i,'region'] = 'Московская обл.'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТРЦ "Корстон"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5209'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [107]:
i=6305
df.loc[df['num_magazine'] == i,'address']='г. Красногорск,  ул. Знаменская, д. 5'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Красногорск'
df.loc[df['num_magazine'] == i,'postal_code']='143402'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'ул. Знаменская'
df.loc[df['num_magazine'] == i,'house'] = 'д. 5'
df.loc[df['num_magazine'] == i,'block'] = '_'
df.loc[df['num_magazine'] == i,'lat'] = '55.818882'
df.loc[df['num_magazine'] == i,'lon'] = '37.346739'
df.loc[df['num_magazine'] == i,'region'] = 'Московская обл.'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "ИЮНЬ"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 6305'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [109]:
i=5411
df.loc[df['num_magazine'] == i,'address']='г. Балашиха, мкр. Ольгино, ул. Главная, д. 2, стр. 1'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Балашиха'
df.loc[df['num_magazine'] == i,'postal_code']='143989'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'мкр. Ольгино, ул. Главная'
df.loc[df['num_magazine'] == i,'house'] = 'д. 2'
df.loc[df['num_magazine'] == i,'block'] = 'стр. 1'
df.loc[df['num_magazine'] == i,'lat'] = '55.750722'
df.loc[df['num_magazine'] == i,'lon'] = '37.992772'
df.loc[df['num_magazine'] == i,'region'] = 'Московская обл.'
df.loc[df['num_magazine'] == i,'magazine'] = ' ТЦ "Малахит"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5411'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [111]:
i=5957
df.loc[df['num_magazine'] == i,'address']='г. Красноярск, ул. 9 Мая, д. 77'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Красноярск'
df.loc[df['num_magazine'] == i,'postal_code']='660125'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'ул. 9 Мая'
df.loc[df['num_magazine'] == i,'house'] = 'д. 77'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '56.050918'
df.loc[df['num_magazine'] == i,'lon'] = '92.904378'
df.loc[df['num_magazine'] == i,'region'] = 'Красноярский край'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТРЦ "Планета"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5957'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [114]:
i=5887
df.loc[df['num_magazine'] == i,'address']='г. Москва, ул. Кировоградская, д.13А'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Москва'
df.loc[df['num_magazine'] == i,'postal_code']='117519'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'ул. Кировоградская'
df.loc[df['num_magazine'] == i,'house'] = 'д. 13А'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '55.612146'
df.loc[df['num_magazine'] == i,'lon'] = '37.606999'
df.loc[df['num_magazine'] == i,'region'] = 'Московский регион'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "Колумбус"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5887'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [116]:
i=6495
df.loc[df['num_magazine'] == i,'address']='г. Санкт-Петербург,  пр-т Испытателей, д.5, к.2, лит.А'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Санкт-Петербург'
df.loc[df['num_magazine'] == i,'postal_code']='197341'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'пр-т Испытателей'
df.loc[df['num_magazine'] == i,'house'] = 'д. 5'
df.loc[df['num_magazine'] == i,'block'] = 'лит А'
df.loc[df['num_magazine'] == i,'lat'] = '60.003966'
df.loc[df['num_magazine'] == i,'lon'] = '30.301495'
df.loc[df['num_magazine'] == i,'region'] = 'Ленинградская область'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "Сити Молл"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5887'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [119]:
i=6495
df.loc[df['num_magazine'] == i,'address']='г. Дубна, пр-т Боголюбова, д. 24А'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Дубна'
df.loc[df['num_magazine'] == i,'postal_code']='141981'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'пр-т Боголюбова'
df.loc[df['num_magazine'] == i,'house'] = 'д. 24А'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '56.735851'
df.loc[df['num_magazine'] == i,'lon'] = '37.157015'
df.loc[df['num_magazine'] == i,'region'] = 'Московская область'
df.loc[df['num_magazine'] == i,'magazine'] = ' ТЦ "Маяк"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5887'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [121]:
i=5741
df.loc[df['num_magazine'] == i,'address']='г. Кемерово, Советский просп., 25/1'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Кемерово'
df.loc[df['num_magazine'] == i,'postal_code']='650000'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'Советский просп.'
df.loc[df['num_magazine'] == i,'house'] = 'д. 25/5'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '55.359451'
df.loc[df['num_magazine'] == i,'lon'] = '86.065360'
df.loc[df['num_magazine'] == i,'region'] = 'Московская область'
df.loc[df['num_magazine'] == i,'magazine'] = '-'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5741'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [123]:
i=5766
df.loc[df['num_magazine'] == i,'address']='г. Тюмень,  ул. Дмитрия Менделеева, д. 1а'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Тюмень'
df.loc[df['num_magazine'] == i,'postal_code']='625062'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'ул. Дмитрия Менделеева'
df.loc[df['num_magazine'] == i,'house'] = 'д. 1а'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '57.116629'
df.loc[df['num_magazine'] == i,'lon'] = '65.551935'
df.loc[df['num_magazine'] == i,'region'] = 'Тюменская область'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТЦ "Кристалл"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5766'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [126]:
i=5816
df.loc[df['num_magazine'] == i,'address']='г. Иркутск, ул. Верхняя Набережная, д.10'
df.loc[df['num_magazine'] == i,'country']='Россия'
df.loc[df['num_magazine'] == i,'city']='г. Иркутск'
df.loc[df['num_magazine'] == i,'postal_code']='664022'
df.loc[df['num_magazine'] == i,'country_iso_code'] = '643'
df.loc[df['num_magazine'] == i,'city_district'] = df['city']
df.loc[df['num_magazine'] == i,'street'] = 'ул. Верхняя Набережная'
df.loc[df['num_magazine'] == i,'house'] = 'д. 10'
df.loc[df['num_magazine'] == i,'block'] = '-'
df.loc[df['num_magazine'] == i,'lat'] = '52.267658'
df.loc[df['num_magazine'] == i,'lon'] = ', 104.289140'
df.loc[df['num_magazine'] == i,'region'] = 'Иркутская область'
df.loc[df['num_magazine'] == i,'magazine'] = 'ТРЦ "ЯркоМолл"'
df.loc[df['num_magazine'] == i,'tsp_name'] = 'Спортмастер 5816'
df.loc[df['num_magazine'] == i,'legal_name'] = 'ООО "СПОРТМАСТЕР"'
#df.loc[df['num_magazine'] == i,'inn'] = '7728551528'
#df.loc[df['num_magazine'] == i]

In [124]:
df.to_csv('VTB.csv')